# Generated by Django 4.0.4 on 2022-05-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='is_publushed',
            new_name='is_published',
        ),
    ]
